document.writeln("<link rel=\"stylesheet\" href=\"css/hanweb.css\">");
document.writeln("<style>");
document.writeln("    .footer{min-width:1241px;height:224px;background:#f1f1f1;}");
document.writeln("    .dxc-linksBox{width:100%;height:66px;font-size:14px;background:#9c020d;}");
document.writeln("    .dxc-linksBox .bt-box-1200{width:1200px;}");
document.writeln("    .dxc-linksBox p{display:inline-block;width:700px;height:33px;line-height:33px;font-size:14px;color:#fff;}");
document.writeln("    .dxc-linksBox span{margin-right:10px;color:#fff;}");
document.writeln("    .dxc-linksBox a{margin-right:40px;color:#fff;}");
document.writeln("    .dxc-linksBox a:hover{color:#fff;}");
document.writeln("    .dxc-copyrightBox{margin:0 auto;width:1200px;height:158px;}");
document.writeln("    .dxc-sydwBox{float:left;height:158px;line-height:158px;}");
document.writeln("    .dxc-copyrightBox a:hover{color:#333;}");
document.writeln("    .dxc-copyrightBox>p{float:left;margin-left:30px;padding-top:50px;height:158px;line-height:28px;font-size:14px;}");
document.writeln("    .dxc-xmtBox{float:right;padding-top:20px;width:433px;height:158px;}");
document.writeln("    .dxc-xmtBox p{float:left;margin-right:47px;line-height:40px;font-size:14px;text-align:center;}");
document.writeln("    .dxc-xmtBox p:last-child{margin-right:0;}");
document.writeln("</style>");
document.writeln("<!--[if gte IE 7]>  ");
document.writeln("<style>");
document.writeln(".hideLinkIframe{display: none;}");
document.writeln("</style>");
document.writeln("<![endif]-->");
document.writeln("<div class=\"footer\">");
document.writeln("    <div class=\"dxc-linksBox\">");
document.writeln("        <div class=\"bt-box-1200\"  style=\"position:relative;\">");
document.writeln("            <p style=\"position: absolute;left: 0px;\">");
document.writeln("                <span>友情链接：</span><a href=\"http://www.moe.gov.cn/\" target=\"_blank\">中华人民共和国教育部</a><a href=\"http://edu.shandong.gov.cn/\" target=\"_blank\">山东省教育厅</a><a href=\"http://jnedu.jinan.gov.cn/\" target=\"_blank\">济南市教育局</a><a href=\"http://jnjyy.jinan-edu.cn/\" target=\"_blank\">济南市教育教学研究院</a> ");
document.writeln("            </p>");
document.writeln("            <a style=\'font-weight: bold;position: absolute;right: 185px;top: 0px;height: 33px;line-height: 33px;\'>校长邮箱：jndxcshiyan@jn.shandong.cn</a>");
document.writeln("            <p style=\"position: absolute;left: 0px;top: 33px;\">");
document.writeln("                <span>教育集团成员校：</span><a href=\"http://sdshiyan.jinan-edu.cn/\" target=\"_blank\">山东省实验中学</a><a href=\"http://jnxcshiyan.jinan-edu.cn/\" target=\"_blank\">济南西城实验中学</a><a href=\"http://xhshiyan.jinan-edu.cn/\" target=\"_blank\">济南新航实验外国语学校</a>");
document.writeln("            </p>");
document.writeln("            <a style=\'font-weight: bold;position: absolute;right: 280px;top: 33px;height: 33px;line-height: 33px;\'>监督电话：0531-89616800</a>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\"dxc-copyrightBox\">");
document.writeln("        <div class=\"dxc-sydwBox\">");
document.writeln("            <a target=\"_blank\">");
document.writeln("                <img id=\"imgConac\" vspace=\"0\" hspace=\"0\" border=\"0\" src=\"http://dcs.conac.cn/image/blue.png\" data-bd-imgshare-binded=\"1\">");
document.writeln("            </a>");
document.writeln("        </div>");
document.writeln("        <p>");
document.writeln("            大学城校地址：济南市大学城瓦特路568号  电话：0531-89616800  邮编：250399<br>");
document.writeln("            COPYRIGHT© 山东省实验中学POWERED BY <a target=\"_blank\" rel=\"noopener noreferrer\">鲁ICP备2023005780号-1</a> <a target=\"_blank\" rel=\"noopener noreferrer\">鲁公网安备37010202700286号</a>");
document.writeln("        </p>");
document.writeln("        <div class=\"dxc-xmtBox\">");
document.writeln("            <p><img src=\"images/2105190949223801776.png\" alt=\"学校微博二维码\"><br>学校微博二维码</p>");
document.writeln("            <p><img src=\"images/2105190949224364783.png\" alt=\"学校微信公众号二维码\"><br>学校微信公众号二维码</p>");
document.writeln("            <p style=\"margin-right:0;\"><img src=\"images/2105190949224057823.png\" alt=\"官方抖音\"><br>官方抖音</p>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("");