document.writeln("<script src=\"script/jslib/Date.js\"></script>");
document.writeln("<link rel=\"stylesheet\" href=\"css/hanweb.css\">");
document.writeln("<style>");
document.writeln("    .header{min-width:1241px;height:205px;background:url(images/headerBg.jpg) no-repeat center top;}");
document.writeln("    *{outline:0!important;}");
document.writeln("    .bt-box-1200{width:1241px;height:auto;margin:0 auto;}");
document.writeln("    .clearfix:after{content:\".\";display:block;clear:both;font-size:0px;height:0px;}");
document.writeln("    .header .dxc-navBox{margin-top:30px;height:49px;}");
document.writeln("    .dxc-logoBox{float:left;margin-top:30px;width:469px;height:95px;background:url(images/Logo.png) no-repeat center;}");
document.writeln("    .dxc-searchBox{float:right;margin-top:35px;width:372px;height:90px;overflow: hidden;}");
document.writeln("    .dxc-searchBox p{margin-top:10px;margin-bottom:10px;}");
document.writeln("    .dxc-searchBox p span{line-height:28px;font-size:14px;color:#fff;}");
document.writeln("    .dxc-searchBox p a{display: inline-block;margin-left: 10px;width: 90px;border-radius: 15px;border: 1px solid #fff;text-align: center;}");
document.writeln("    .dxc-search{width:372px;height:38px;line-height:38px;float: right;}");
document.writeln("    .dxc-search input{float:left;padding-left:17px;width:302px;height:38px;line-height:38px;color:#666666;border:0;outline:none;border-top-left-radius:8px;border-bottom-left-radius:8px;border-top-right-radius:0;border-bottom-right-radius:0;}");
document.writeln("    .dxc-search button{float:left;width:66px;height:38px;border:0;border-top-right-radius:8px;outline:none;border-bottom-right-radius:8px;border-top-left-radius:0;border-bottom-left-radius:0;background:#fff url(images/searchBtn.png) no-repeat center;}");
document.writeln("    .dxc-navBox{margin-top:30px;height:49px;}");
document.writeln("    .dxc-navBox ul li{position:relative;float:left;margin-right:6px;width:107px;height:50px;line-height:50px;font-size:16px;text-align:center;color:#ffffff;cursor:pointer;}");
document.writeln("    .dxc-navBox ul li.active {background: #a7181f;}");
document.writeln("    .dxc-navBox ul li:hover {background: #a7181f;}");
document.writeln("    .dxc-navBox ul li:last-child {margin-right: 0;}");
document.writeln("    .dxc-navBox ul li>a {display: block;text-align: center;color: #ffffff;}");
document.writeln("    .dxc-hideNav{position:absolute;z-index:999;width:100%;background:#FFFFFF;border-bottom-left-radius:5px;border-bottom-right-radius:5px;}");
document.writeln("    .dxc-hideNav p:last-child{border-bottom-left-radius:5px;border-bottom-right-radius:5px;}");
document.writeln("    .dxc-hideNav p:last-child a{border-bottom-left-radius:5px;border-bottom-right-radius:5px;}");
document.writeln("    .dxc-hideNav a{display:block;font-size:14px;color:#333333;}");
document.writeln("    .dxc-hideNav a:hover {color: #fff;background: #a7181f;}");
document.writeln("    .toolbar_bottom li,.toolbar_bottom {box-sizing: content-box;    line-height: 28px !important;}");
document.writeln("</style>");
document.writeln("");
document.writeln("<div class=\"header\">");
document.writeln("    <div class=\"bt-box-1200 clearfix\">");
document.writeln("        <span class=\"dxc-logoBox\"></span>");
document.writeln("        <div class=\"dxc-searchBox\">");
document.writeln("            <p>");
document.writeln("                <span id=\"Date\"></span>");
document.writeln("<a href=\'javascript:;\' onclick=\'toggleToolBar();\'><span>无障碍阅读</span></a>");
document.writeln("            </p>");
document.writeln("             <script>");
document.writeln("                    $(function () {");
document.writeln("                        var lunar = calendar.solar2lunar();");
document.writeln("                        $(\'#Date\').html(lunar.cYear + \'年\' + lunar.cMonth + \'月\' + lunar.cDay + \'日 \' + lunar.ncWeek +   \' \' + lunar.gzYear + \'年\' + lunar.IMonthCn + lunar.IDayCn);");
document.writeln("                    });");
document.writeln("            </script>");
document.writeln("            <div class=\"dxc-search\">");
document.writeln("                <form name=\"qForm\" action=\"/api-gateway/jpaas-jsearch-web-server/search\" method=\"get\" target=\"_blank\" onsubmit=\"return  checkFormguolv()\">");
document.writeln("                    <input type=\"hidden\" name=\"serviceId\" value=\"71SQblMnojUt6kKnB1eom\" aria-valuenow=\"71SQblMnojUt6kKnB1eom\" role=\"hidden\" aria-readonly=\"true\">");
document.writeln("                    <input type=\"text\" id=\"q\" name=\"q\" height=\"20\" class=\"searchtext\" onfocus=\"if(this.value==\'请输入关键字\'){this.value=\'\'}\" onblur=\"if(this.value==\'\'){this.value=\'请输入关键字\'}\" value=\"请输入关键字\" autocomplete=\"off\">");
document.writeln("                    <button id=\'searchBtn\' type=\"submit\"></button>");
document.writeln("            </form>");
document.writeln("            <script language=\"javascript\">");
document.writeln("	function checkFormguolv(){");
document.writeln("		var oTxe=document.getElementById(\'q\');");
document.writeln("		if (oTxe.value==\'请输入关键字\' || oTxe.value==\'\'){");
document.writeln("			alert(\'请输入关键字!\')");
document.writeln("			oTxe.value=\'\';");
document.writeln("			return false;}");
document.writeln("	}");
document.writeln("</script>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\"bt-box-1200 dxc-navBox\">");
document.writeln("        <ul>");
document.writeln("            <li><a href=\"/\">首 页</a>");
document.writeln("            </li>");
document.writeln("            <li style=\"cursor: default;\">学校概况");
document.writeln("                <div class=\"dxc-hideNav\" style=\"display: none;\">");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5212/index.html\" rel=\"noopener noreferrer\">学校简介</a></p>");
//document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5215/index.html\" rel=\"noopener noreferrer\">学校领导</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5213/index.html\" rel=\"noopener noreferrer\">校园美景</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col12674/index.html\" rel=\"noopener noreferrer\">管理团队</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col12712/index.html\" rel=\"noopener noreferrer\">机构设置</a></p>");
document.writeln("                </div>");
document.writeln("            </li>");
document.writeln("            <li style=\"cursor: default;\">党群之窗");
document.writeln("                <div class=\"dxc-hideNav\" style=\"display: none;\">");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5217/index.html\" rel=\"noopener noreferrer\">党建动态</a></p>");
document.writeln("                    <p style=\"line-height:22px;\"><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5218/index.html\" rel=\"noopener noreferrer\">不忘初心，牢记使命</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5358/index.html\" rel=\"noopener noreferrer\">主题教育</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5359/index.html\" rel=\"noopener noreferrer\">党史学习</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5360/index.html\" rel=\"noopener noreferrer\">工团活动</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5567/index.html\" rel=\"noopener noreferrer\">统战工作</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5568/index.html\" rel=\"noopener noreferrer\">党员风采</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5576/index.html\" rel=\"noopener noreferrer\">督导纪检</a></p>");
document.writeln("                </div>");
document.writeln("            </li>");
document.writeln("            <li style=\"cursor: default;\">招生专栏");
document.writeln("                <div class=\"dxc-hideNav\" style=\"display: none;\">");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5266/2026n/index.html\" rel=\"noopener noreferrer\">2026年</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5266/2025/index.html\" rel=\"noopener noreferrer\">2025年</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col12673/index.html\" rel=\"noopener noreferrer\">2024年</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col10014/index.html\" rel=\"noopener noreferrer\">2023年</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col6047/index.html\" rel=\"noopener noreferrer\">2022年</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5356/index.html\" rel=\"noopener noreferrer\">2021年</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5355/index.html\" rel=\"noopener noreferrer\">2020年</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5354/index.html\" rel=\"noopener noreferrer\">2019年</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5353/index.html\" rel=\"noopener noreferrer\">2018年</a></p>");
document.writeln("                </div>");
document.writeln("            </li>");
document.writeln("            <li style=\"cursor: default;\">师资队伍");
document.writeln("                <div class=\"dxc-hideNav\" style=\"display: none;\">");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5228/index.html\" rel=\"noopener noreferrer\">名师风采</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5416/index.html\" rel=\"noopener noreferrer\">师资介绍</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5225/index.html\" rel=\"noopener noreferrer\">发展指导</a></p>");
document.writeln("                </div>");
document.writeln("            </li>");
document.writeln("            <li style=\"cursor: default;\">德育天地");
document.writeln("                <div class=\"dxc-hideNav\" style=\"display: none;\">");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5249/index.html\" rel=\"noopener noreferrer\">德育活动</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5361/index.html\" rel=\"noopener noreferrer\">品牌探索</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5362/index.html\" rel=\"noopener noreferrer\">团队建设</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5417/index.html\" rel=\"noopener noreferrer\">学子风采</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5252/index.html\" rel=\"noopener noreferrer\">志愿服务</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5418/index.html\" rel=\"noopener noreferrer\">畅通心语</a></p>");
document.writeln("                </div>");
document.writeln("            </li>");
document.writeln("            <li style=\"cursor: default;\">课程教研");
document.writeln("                <div class=\"dxc-hideNav\" style=\"display: none;\">");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5221/index.html\" rel=\"noopener noreferrer\">教研活动</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5223/index.html\" rel=\"noopener noreferrer\">双高联育</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5220/index.html\" rel=\"noopener noreferrer\">多元课程</a></p>");
//document.writeln("/*                     <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5224/index.html\" rel=\"noopener noreferrer\">语言文学</a></p> */");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5260/index.html\" rel=\"noopener noreferrer\">品牌创建</a></p>");
document.writeln("                </div>");
document.writeln("            </li>");
document.writeln("            <li style=\"cursor: default;\">文明校园");
document.writeln("                <div class=\"dxc-hideNav\" style=\"display: none;\">");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5575/index.html\" rel=\"noopener noreferrer\">领导班子建设</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5422/index.html\" rel=\"noopener noreferrer\">思想道德教育</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5425/index.html\" rel=\"noopener noreferrer\">活动阵地</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5423/index.html\" rel=\"noopener noreferrer\">教师队伍</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5426/index.html\" rel=\"noopener noreferrer\">校园文化</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5424/index.html\" rel=\"noopener noreferrer\">校园环境</a></p>");
document.writeln("                </div>");
document.writeln("            </li>");
document.writeln("            <li style=\"cursor: default;\">交流合作");
document.writeln("                <div class=\"dxc-hideNav\" style=\"display: none;\">");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5571/index.html\" rel=\"noopener noreferrer\">国内交流</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5572/index.html\" rel=\"noopener noreferrer\">国际交流</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5573/index.html\" rel=\"noopener noreferrer\">出国升学</a></p>");
document.writeln("                </div>");
document.writeln("            </li>");
document.writeln("            <li style=\"cursor: default;\">校友风采");
document.writeln("                <div class=\"dxc-hideNav\" style=\"display: none;\">");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5574/index.html\" rel=\"noopener noreferrer\">首届校友</a></p>");
document.writeln("                </div>");
document.writeln("            </li>");
document.writeln("            <li style=\"cursor: default;\">信息公开");
document.writeln("                <div class=\"dxc-hideNav\" style=\"display: none;\">");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5270/index.html\" rel=\"noopener noreferrer\">作息时间表</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5271/index.html\" rel=\"noopener noreferrer\">课程表</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5408/index.html\" rel=\"noopener noreferrer\">餐卡充值</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5272/index.html\" rel=\"noopener noreferrer\">图书馆</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5427/index.html\" rel=\"noopener noreferrer\">教师招聘</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5409/index.html\" rel=\"noopener noreferrer\">财务公开</a></p>");
document.writeln("                    <p><a href=\"https://jndxcshiyan.jinan-edu.cn/col/col5410/index.html\" rel=\"noopener noreferrer\">收费标准</a></p>");
document.writeln("                </div>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<script type=\"text/javascript\">");
document.writeln("    $(function () {");
document.writeln("        // 搜索框提示");
document.writeln("        $(\"#searchBtn\").click(function () {");
document.writeln("            if ($(\"#q\").val() == \'请输入关键字\') {");
document.writeln("                alert(\"请输入关键字！\")");
document.writeln("                return false;");
document.writeln("            } else if ($(\"#q\").val().replace(/\\s+/g, \"\").length == 0) {");
document.writeln("                alert(\"请输入关键字！\")");
document.writeln("                return false;");
document.writeln("            }");
document.writeln("        })");
document.writeln("        // nav下拉");
document.writeln("        $(\'.dxc-navBox li\').hover(function () {");
document.writeln("            $(this).find(\'.dxc-hideNav\').show();");
document.writeln("        }, function () {");
document.writeln("            $(this).find(\'.dxc-hideNav\').hide();");
document.writeln("        });");
document.writeln("    })");
document.writeln("</script>");

document.writeln("<style type=\"text/css\">");
document.writeln("	.dxc-navBox ul li:hover .dxc-hideNav{");
document.writeln("		display: block !important;");
document.writeln("	}");
document.writeln("</style>");

		// nav下拉
 const navItems = document.querySelectorAll('.dxc-navBox ul li');
        navItems.forEach(item => {
            const subMenu = item.querySelector('.dxc-hideNav');
            if (subMenu) {
                item.addEventListener('mouseenter', () => {
                    subMenu.style.display = 'block';
                });
                item.addEventListener('mouseleave', () => {
                    subMenu.style.display = 'none';
                });
            }
        });